### ISSUE TITLE
Don't work with Android Studio 4.1

### ISSUE THREAD

**Issue by PhanPirang** [itkacher/OkHttpProfiler#19] opened 2020-10-13 06:01 UTC

**Comment by Rondaul** [comment] 2020-10-15 05:14
@gektor650 Hi, what's the update on this fix? I really like this plugin. Makes it really easy to see api request and responses. Hope it gets fix soon. ❤️

**Comment by gektor650** [comment] 2020-10-15 16:36
@Rondaul @AlienAsRoger @PhanPirang I uploaded version 1.0.12 with a fix for Android Studio
But now IntelliJ IDEA has a backward error 
`Incompatible change of interface Client to class`
Unfortunately, Google decided to change realization, but Intellij doesn't. 
JetBrains will review in two business days.
Before the review, you can use the direct install of the plugin. Not sure if it will be successful. 

**But you can use the fix right now:**

1. Go to the [Version 1.0.12](https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/99716).
2. Open your android studio.
3. Go to the Android Studio Preferences -> Plugins -> Press settings -> Install Plugin From Disk...
4. Choose the Zip file and restart the studio. 
Also, I will add Zip & Description to the Readme of the repository and I will add a zip of the plugin.
I will add a description to the repo.

**Comment by AlienAsRoger** [comment] 2020-10-15 22:51
> @Rondaul @AlienAsRoger @PhanPirang I uploaded version 1.0.12 with a fix for Android Studio
> But now IntelliJ IDEA has a backward error
> `Incompatible change of interface Client to class`
> Unfortunately, Google decided to change realization, but Intellij doesn't.
> JetBrains will review in two business days.
> Before the review, you can use the direct install of the plugin. Not sure if it will be successful.
> 
> **But you can use the fix right now:**
> 
> 1. Go to the [Version 1.0.12](https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/99716).
> 2. Open your android studio.
> 3. Go to the Android Studio Preferences -> Plugins -> Press settings -> Install Plugin From Disk...
> 4. Choose the Zip file and restart the studio.
>    Also, I will add Zip & Description to the Readme of the repository and I will add a zip of the plugin.
>    I will add a description to the repo.

Thank you so much! This works!

**Comment by PhanPirang** [comment] 2020-10-16 02:16
> @Rondaul @AlienAsRoger @PhanPirang I uploaded version 1.0.12 with a fix for Android Studio
> But now IntelliJ IDEA has a backward error
> `Incompatible change of interface Client to class`
> Unfortunately, Google decided to change realization, but Intellij doesn't.
> JetBrains will review in two business days.
> Before the review, you can use the direct install of the plugin. Not sure if it will be successful.
> 
> **But you can use the fix right now:**
> 
> 1. Go to the [Version 1.0.12](https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/99716).
> 2. Open your android studio.
> 3. Go to the Android Studio Preferences -> Plugins -> Press settings -> Install Plugin From Disk...
> 4. Choose the Zip file and restart the studio.
>    Also, I will add Zip & Description to the Readme of the repository and I will add a zip of the plugin.
>    I will add a description to the repo.

Thanks you so much!

**Comment by cenkgun** [comment] 2020-10-16 06:09
> @Rondaul @AlienAsRoger @PhanPirang I uploaded version 1.0.12 with a fix for Android Studio
> But now IntelliJ IDEA has a backward error
> `Incompatible change of interface Client to class`
> Unfortunately, Google decided to change realization, but Intellij doesn't.
> JetBrains will review in two business days.
> Before the review, you can use the direct install of the plugin. Not sure if it will be successful.
> 
> **But you can use the fix right now:**
> 
> 1. Go to the [Version 1.0.12](https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/99716).
> 2. Open your android studio.
> 3. Go to the Android Studio Preferences -> Plugins -> Press settings -> Install Plugin From Disk...
> 4. Choose the Zip file and restart the studio.
>    Also, I will add Zip & Description to the Readme of the repository and I will add a zip of the plugin.
>    I will add a description to the repo.

Hi @gektor650 !
Thank you for quick reaction but this version seems incompatible with android studio 4.1
![image](https://user-images.githubusercontent.com/9965508/96219189-f67b9900-0f8e-11eb-9376-35c6a306e326.png)

**Comment by gektor650** [comment] 2020-10-17 10:10
I will appreciate if you also vote for the issue on the JetBrains forum:
[https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009828200-Android-Studio-4-1-com-android-ddmlib-Client-changed-from-class-to-interface-Now-it-s-incompatible-with-an-IntelliJ-IDEA](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009828200-Android-Studio-4-1-com-android-ddmlib-Client-changed-from-class-to-interface-Now-it-s-incompatible-with-an-IntelliJ-IDEA )

**Comment by gektor650** [comment] 2020-10-17 14:19
@cenkgun Hi! Just don't trust this message :) 
 After restart of the Android Studio you will not see the message. 
I added version 1.0.13 with the fixed platforms
[Supported Products: Android Studio — build 201.8743.12+](https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/99848)

**Comment by Rondaul** [comment] 2020-10-19 05:17
> I will appreciate if you also vote for the issue on the JetBrains forum:
> https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009828200-Android-Studio-4-1-com-android-ddmlib-Client-changed-from-class-to-interface-Now-it-s-incompatible-with-an-IntelliJ-IDEA

Done! 👍

**Comment by Rondaul** [comment] 2020-10-19 05:20
> @Rondaul @AlienAsRoger @PhanPirang I uploaded version 1.0.12 with a fix for Android Studio
> But now IntelliJ IDEA has a backward error
> `Incompatible change of interface Client to class`
> Unfortunately, Google decided to change realization, but Intellij doesn't.
> JetBrains will review in two business days.
> Before the review, you can use the direct install of the plugin. Not sure if it will be successful.
> 
> **But you can use the fix right now:**
> 
> 1. Go to the [Version 1.0.12](https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/99716).
> 2. Open your android studio.
> 3. Go to the Android Studio Preferences -> Plugins -> Press settings -> Install Plugin From Disk...
> 4. Choose the Zip file and restart the studio.
>    Also, I will add Zip & Description to the Readme of the repository and I will add a zip of the plugin.
>    I will add a description to the repo.

And thank you for the quick fix. Hope the issue with class to interface change gets resolved by jetbrains team soon so it works on both intellij idea and android studio. I request everyone to plz vote on the support link above. 🙏

**Comment by gektor650** [comment] 2020-10-19 13:27
Version 1.0.13 approved by JetBrains. The issue is solved. 
If I find a way to support Android Studio AND Intellij IDEA - I will add implementation.

**Closed by gektor650** 2020-10-19 13:27 UTC
Labels: Fix Submitted, In Progress, bug
